export const APP_UPDATE = 'APP_UPDATE'
export const APP_SETTINGS_UPDATE = 'APP_SETTINGS_UPDATE'

export const KAFKA_UPDATE = 'KAFKA_UPDATE'
export const KAFKA_BREADCRUMBS_UPDATE = 'KAFKA_BREADCRUMBS_UPDATE'